### ISSUE TITLE
Connect to cluster from outside

### ISSUE THREAD

**Issue by teawithfruit** [Yolean/kubernetes-mysql-cluster#23]
Hello,

Thank you for providing this repo.
I set up a running cluster, but I can't connect to it form outside. So my question is the following.

What is the best way, to connect to the running cluster?
I've tried it with the following config, but had no success.

```
apiVersion: v1
kind: Service
metadata:
  name: mariadbport
  namespace: mysql
spec:
  ports:
  - nodePort: 30306
    port: 3306
  selector:
    app: mariadb
  type: NodePort
```

I've also installed the phpmyadmin config, but there is no IP provided which I can use in my browser to look inside phpmyadmin.
How do you look inside a running database cluster, to maybe check something inside the database?

Thank's for your help.
